config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'home#index'

  get 'edit_profile/:id', to: 'profiles#edit_profile', as: 'edit_profile'
  put 'update_profile/:id', to: 'profiles#update_profile', as: 'update_profile'
  get 'advantage/:id', to: 'advantages#show', as: 'advantage'
  get '/projects/:alias', to: 'projects#show', as: 'projects'
  post '/feedback', to: 'feedback#send_feedback'
  resources :subscribers, only: :create

  namespace :admin do
    root to: 'home#index'
    resources :menus
    resources :materials
    resources :tags, except: :show
    resources :users, only: %i[index edit update]
    resources :sliders, except: :show
    resources :articles
    resources :videos
    resources :advantages
    resources :projects
    resources :potential_investors, only: %i[index show]
    resources :submission_projects, only: %i[index show]
    resources :contents, only: %i[index edit update]
    resources :departments
    resources :teams
    resources :reviews
    resources :block_materials
    resources :balancers
    resources :sectors, exept: %i[show]
    resources :trips, exept: %i[show]
    resources :landmarks, exept: %i[show]
    resources :period_events, exept: %i[show]
    resources :abouts, exept: %i[show new create]
  end

  namespace :cabinet do
    root to: 'home#index'
    resources :production_areas
    resources :land_areas
    resources :office_areas
    resources :communal_areas
    get 'geo_json/:model/:id', to: 'geo_json#index'
    resources :users, only: %i[index edit update]
    resources :map_layers, except: %i[show]
    resources :potential_investors, only: %i[index show]
    resources :submission_projects, only: %i[index show]
    resources :balancers
    resources :area_logs, only: :index
    resources :communal_areas
    resources :transports
    resources :ownerships
    resources :infrastructure_types
    resources :invest_projects
    resources :map_layer_groups
  end

  namespace :api do
    namespace :v1 do
      resources :map_objects, only: :index
      get '/map_objects/:model/:id', to: 'map_objects#show'
      get '/layer_links', to: 'map_objects#layer_links'
    end
  end

  scope '(:locale)', locale: /uk|en/ do
    get '/guide', to: 'home#guide'
    get '/tourism', to: 'home#tourism'
    get '/about', to: 'abouts#index'
    get 'geo_json_gis', to: 'maps#geo_json_gis', as: :geo_json_gis
    get 'init_map_layers', to: 'maps#map_layers', as: :init_map_layers
    get 'select_object_info', to: 'invest_maps#select_object_info', as: :select_object_info
    root to: 'home#index'
    resources :invest_maps, only: :index
    resources :production_areas, only: :show
    resources :land_areas, only: :show
    resources :office_areas, only: :show
    resources :communal_areas, only: :show
    resources :invest_projects, only: :show
    resources :projects, only: :index
    resources :landmarks, only: :index
    get '/projects/:alias', to: 'projects#show'
    resources :sectors, only: %i[index]
    get 'articles', to: 'articles#index', as: :articles
    get 'articles/:id', to: 'articles#show', as: :article
    resources :user_land_areas, only: :create
    resources :potential_investors, only: :create
    get 'reviews', to: 'reviews#index', as: 'reviews'
    resources :submission_projects, only: :create
    get 'our_team', to: 'teams#index', as: 'our_team'
    get '/search', to: 'elastic#search', as: :search
    resources :materials, only: %i[index]
    resources :materials, only: :show, path: '/'
  end

  match '*path', to: 'application#not_found', via: :all
end

app/models/project.rb
class Project < ApplicationRecord
  include ProjectImageUrl

  translates :title, :description, :short_description, fallbacks_for_empty_translations: true
  globalize_accessors locales: %i[uk en], attributes: %i[title description short_description]

  has_many :project_images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :project_images, allow_destroy: true, reject_if: proc { |att| att['image'].blank? }

  validates :title_uk, :title_en, presence: { message: I18n.t('blank') }
  validate :blank_images

  scope :by_locale, ->(locale) { where(locale: locale) }

  def image
    project_images.by_locale(I18n.locale).first || project_images.first
  end

  def blank_images
    errors.add(:image, 'Поле не може бути пустим') if project_images.blank?
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  before_action :set_project, only: %w[show edit update destroy]

  def index
    @admin_projects = Project.all
  end

  def show; end

  def new
    @admin_project = Project.new
  end

  def edit; end

  def create
    @admin_project = Project.new(admin_project_params)
    if @admin_project.save
      flash[:notice] = t('success_create_notice')
      redirect_to admin_projects_path
    else
      render :new
    end
  end

  def update
    if @admin_project.update(admin_project_params)
      flash[:notice] = t('success_create_notice')
      redirect_to admin_projects_path
    else
      render :edit
    end
  end

  def destroy
    @admin_project.destroy
    flash[:notice] = t('success_delete_notice')
    redirect_to admin_projects_path
  end

  private

  def set_project
    @admin_project = Project.find(params[:id])
  end

  def admin_project_params
    permitted = Project.globalize_attribute_names + [:alias, project_images_attributes:
                                                               %i[id locale image imageable_id imageable_type _destroy]]
    params.require(:project).permit(permitted)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: :show

  def index
    @projects = Project.all
  end

  def show; end

  private

  def set_project
    @project = Project.find_by(alias: params[:alias])
  end
end

app/views/admin/projects/_form.html.slim
.panel-body
  .tab-block.mb25
    = simple_form_for [:admin, @admin_project] do |f|
      ul.nav.tabs-right.tabs-border
        li.active.tab-name
          a[href="#main_uk" data-toggle="tab"]
            | Українською
        li.tab-name
          a[href="#main_en" data-toggle="tab"]
            | Англійською
      .tab-content
        = render 'main_uk', f: f
        = render 'main_en', f: f
      = render 'blocks/btns/save_button', f: f
      = render 'blocks/btns/back', path: admin_projects_path

javascript:
  $(document).ready(function () {
    var options = {
      width: 300,
      height: 200,
      delete_image_uk: $('#project_project_images_attributes_0__destroy'),
      delete_image_en: $('#project_project_images_attributes_1__destroy')
    };

    initCropper('#project_project_images_attributes_0_image', options);
    initEnCropper('#project_project_images_attributes_1_image', options);
  });

app/views/admin/projects/_main_en.html.slim
.tab-pane#main_en
  .form-group
    = f.label :title_en, 'Назва англійською'
    = f.input :title_en, label: false, input_html: { class: 'form-control' }
  .form-group
    = f.label :short_description_en, 'Короткий опис англійською'
    = ckeditor_input(f, :short_description_en, 'en')
  .form-group
    = f.label :description_en, 'Опис англійською'
    = ckeditor_input(f, :description_en, 'en')

  = f.fields_for :project_images, @admin_project.project_images.by_locale('en').first || @admin_project.project_images.build do |f|
    = f.input :locale, as: :hidden, input_html: { value: 'en' }
    .form-group.images-form
      = f.input :id, as: :hidden
      = f.label :image, 'Зображення для англійської версії'
      = f.input :image, as: :hidden
      = f.input :imageable_id, as: :hidden
      = f.input :imageable_type, as: :hidden
      = f.input :_destroy, as: :hidden
      .section
        .row
          .col-sm-6
            label.field.prepend-icon.append-button.file
              input#news-en-img.gui-file name="en_image" type="file"
          .col-sm-6
            .file.prepend-icon.get-image-en
              a.button.btn-default.pull-right#getCroppedEnImage
                | Застосувати
      .section
        .upload-msg-en
          - if @admin_project.project_images.by_locale('en').present?
            = image_tag @admin_project.project_images.by_locale('en').first.image.url, class: 'img-responsive'
            = link_to 'Скинути', '#', class: 'btn btn-default mt10', id: 'resetCroppedEnImg'
          - else
            | Завантажте картинку проекту
        .upload-wrap-en
          #main-cropper-en

app/views/admin/projects/_main_uk.html.slim
.tab-pane.active#main_uk
  .form-group
    = f.label :title_uk, 'Назва українською'
    = f.input :title_uk, label: false, input_html: { class: 'form-control' }
  .form-group
    = f.label :short_description_uk, 'Короткий опис українською'
    = ckeditor_input(f, :short_description_uk)
  .form-group
    = f.label :description_uk, 'Опис українською'
    = ckeditor_input(f, :description_uk)

  .form-group
    = f.label :alias, 'Аліас(без символа /)'
    = f.input :alias, label: false, input_html: { class: 'form-control' }

  = f.fields_for :project_images, @admin_project.project_images.by_locale('uk').first || @admin_project.project_images.build do |f|
    = f.input :locale, as: :hidden, input_html: { value: 'uk' }
    .form-group.images-form
      = f.input :id, as: :hidden
      = f.label :image, 'Зображення для української версії'
      = f.input :image, as: :hidden
      = f.input :imageable_id, as: :hidden
      = f.input :imageable_type, as: :hidden
      = f.input :_destroy, as: :hidden
      .section
        .row
          .col-sm-6
            label.field.prepend-icon.append-button.file
              input#news-img.gui-file name="uk_image" type="file"
          .col-sm-6
            .file.prepend-icon.get-image
              a.button.btn-default.pull-right#getCroppedImage
                | Застосувати
      .section
        .upload-msg
          - if @admin_project.project_images.by_locale('uk').present?
            = image_tag @admin_project.project_images.by_locale('uk').first.image.url, class: 'img-responsive'
            = link_to 'Скинути', '#', class: 'btn btn-default mt10', id: 'resetCroppedImg'
          - else
            | Завантажте картинку проекту
        .upload-wrap
          #main-cropper

app/views/admin/projects/edit.html.slim
h1.center
  | Редагувати проект

= render 'form'

app/views/admin/projects/index.html.slim
h1.center Список проектів

= render 'layouts/general/table', path: new_admin_project_path, title: 'Список тегів' do
  thead
    tr
      th №п/п
      th Назва українською
      th Назва англійською
      th Дії
  tbody
    - @admin_projects.each_with_index do |admin_project, index|
      tr
        td = index + 1
        td = admin_project.title_uk
        td = admin_project.title_en
        td
          = render 'layouts/blocks/action_btns' do
            = render 'blocks/btns/edit', path: edit_admin_project_path(admin_project)
            = render 'blocks/btns/delete', path: admin_project_path(admin_project)

app/views/admin/projects/new.html.slim
h1.center
  | Новий проект

= render 'form'