config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'home#index'

  get 'edit_profile/:id', to: 'profiles#edit_profile', as: 'edit_profile'
  put 'update_profile/:id', to: 'profiles#update_profile', as: 'update_profile'
  get 'advantage/:id', to: 'advantages#show', as: 'advantage'
  get '/projects/:alias', to: 'projects#show', as: 'projects'
  post '/feedback', to: 'feedback#send_feedback'
  resources :subscribers, only: :create

  namespace :admin do
    root to: 'home#index'
    resources :menus
    resources :materials
    resources :tags, except: :show
    resources :users, only: %i[index edit update]
    resources :sliders, except: :show
    resources :articles
    resources :videos
    resources :advantages
    resources :projects
    resources :potential_investors, only: %i[index show]
    resources :submission_projects, only: %i[index show]
    resources :contents, only: %i[index edit update]
    resources :departments
    resources :teams
    resources :reviews
    resources :block_materials
    resources :balancers
    resources :sectors, exept: %i[show]
    resources :trips, exept: %i[show]
    resources :landmarks, exept: %i[show]
    resources :period_events, exept: %i[show]
    resources :abouts, exept: %i[show new create]
  end

  namespace :cabinet do
    root to: 'home#index'
    resources :production_areas
    resources :land_areas
    resources :office_areas
    resources :communal_areas
    get 'geo_json/:model/:id', to: 'geo_json#index'
    resources :users, only: %i[index edit update]
    resources :map_layers, except: %i[show]
    resources :potential_investors, only: %i[index show]
    resources :submission_projects, only: %i[index show]
    resources :balancers
    resources :area_logs, only: :index
    resources :communal_areas
    resources :transports
    resources :ownerships
    resources :infrastructure_types
    resources :invest_projects
    resources :map_layer_groups
  end

  namespace :api do
    namespace :v1 do
      resources :map_objects, only: :index
      get '/map_objects/:model/:id', to: 'map_objects#show'
      get '/layer_links', to: 'map_objects#layer_links'
    end
  end

  scope '(:locale)', locale: /uk|en/ do
    get '/guide', to: 'home#guide'
    get '/tourism', to: 'home#tourism'
    get '/about', to: 'abouts#index'
    get 'geo_json_gis', to: 'maps#geo_json_gis', as: :geo_json_gis
    get 'init_map_layers', to: 'maps#map_layers', as: :init_map_layers
    get 'select_object_info', to: 'invest_maps#select_object_info', as: :select_object_info
    root to: 'home#index'
    resources :invest_maps, only: :index
    resources :production_areas, only: :show
    resources :land_areas, only: :show
    resources :office_areas, only: :show
    resources :communal_areas, only: :show
    resources :invest_projects, only: :show
    resources :projects, only: :index
    resources :landmarks, only: :index
    get '/projects/:alias', to: 'projects#show'
    resources :sectors, only: %i[index]
    get 'articles', to: 'articles#index', as: :articles
    get 'articles/:id', to: 'articles#show', as: :article
    resources :user_land_areas, only: :create
    resources :potential_investors, only: :create
    get 'reviews', to: 'reviews#index', as: 'reviews'
    resources :submission_projects, only: :create
    get 'our_team', to: 'teams#index', as: 'our_team'
    get '/search', to: 'elastic#search', as: :search
    resources :materials, only: %i[index]
    resources :materials, only: :show, path: '/'
  end

  match '*path', to: 'application#not_found', via: :all
end

app/controllers/cabinet/area_logs_controller.rb
class Cabinet::AreaLogsController < Cabinet::CabinetController
  def index
    @area_logs = AreaLog.all
  end
end

app/controllers/cabinet/balancers_controller.rb
class Cabinet::BalancersController < Cabinet::CabinetController
  load_and_authorize_resource
  before_action :set_cabinet_balancer, only: %i[edit update destroy]

  # GET /cabinet/balancers
  # GET /cabinet/balancers.json
  def index
    @cabinet_balancers = Balancer.all
  end

  # GET /cabinet/balancers/new
  def new
    @cabinet_balancer = Balancer.new
  end

  # GET /cabinet/balancers/1/edit
  def edit; end

  # POST /cabinet/balancers
  # POST /cabinet/balancers.json
  def create
    @cabinet_balancer = Balancer.new(create_params)

    respond_to do |format|
      if @cabinet_balancer.save
        format.html { redirect_to cabinet_balancers_path, notice: I18n.t('created') }
        format.json { render :show, status: :created, location: @cabinet_balancer }
      else
        format.html { render :new }
        format.json { render json: @cabinet_balancer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabinet/balancers/1
  # PATCH/PUT /cabinet/balancers/1.json
  def update
    respond_to do |format|
      if @cabinet_balancer.update(create_params)
        format.html { redirect_to cabinet_balancers_path, notice: I18n.t('updated') }
        format.json { render :show, status: :ok, location: @cabinet_balancer }
      else
        format.html { render :edit }
        format.json { render json: @cabinet_balancer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabinet/balancers/1
  # DELETE /cabinet/balancers/1.json
  def destroy
    @cabinet_balancer.destroy
    respond_to do |format|
      format.html { redirect_to cabinet_balancers_path, notice: I18n.t('deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cabinet_balancer
    @cabinet_balancer = Balancer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def create_params
    params.require(:balancer).permit(:name)
  end
end

app/controllers/cabinet/cabinet_controller.rb
module Cabinet
  class CabinetController < ActionController::Base
    include DeleteCropperImage
    before_action :authenticate_user!
    before_action :check_permission
    before_action :set_locale
    around_action :set_current_user

    layout 'cabinet'

    rescue_from CanCan::AccessDenied do |_exception|
      redirect_to cabinet_root_path
    end

    private

    def check_permission
      redirect_back(fallback_location: root_path) unless current_user.has_any_role?(:questionnaire, :moderator)
    end

    def gis_types
      @gis_types = GisType.all[0..2]
      @balancers = Balancer.all.pluck(:name, :id)
      @infrastructure_types = InfrastructureType.eager_load(:translations).map { |e| [e.name, e.id] }
    end

    def available_states
      except = current_user.moderator? ? [] : %w[published archived]
      @states = Questionnaire.states_with_except(except)
    end

    def set_locale
      I18n.locale = I18n.default_locale
    end

    def set_current_user
      require 'current'
      Current.user = current_user
      yield
    ensure
      Current.user = nil
    end
  end
end

app/controllers/cabinet/communal_areas_controller.rb
class Cabinet::CommunalAreasController < Cabinet::CabinetController
  before_action :gis_types, only: %i[new create edit update]
  before_action :available_states, only: %i[new create edit update]
  before_action :set_cabinet_communal_area, only: %i[show edit update destroy]
  before_action :select_selected_fields, only: %i[new edit create update]
  load_and_authorize_resource

  include QuestionnaireImages
  include QuestionnaireValidation
  include StateMachine

  def index
    areas = CommunalArea.all
    areas = areas.by_status(params[:search_by_status]) if params[:search_by_status].present?
    areas = areas.by_balancer(params[:search_by_balancer]) if params[:search_by_balancer].present?
    areas = areas.by_name(params[:search_by_name]) if params[:search_by_name].present?
    areas = areas.by_map_layer(params[:search_by_map_layer]) if params[:search_by_map_layer].present?
    @cabinet_communal_areas = areas.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  def new
    @cabinet_communal_area = current_user.communal_areas.new
  end

  def edit; end

  def create
    @cabinet_communal_area = current_user.communal_areas.new(create_params)
    respond_to do |format|
      if status_valid?(create_params[:status]) && @cabinet_communal_area.save
        QuestionnaireImages.build(params, @cabinet_communal_area)
        public_send(params[:communal_area][:status])
        format.html { redirect_to cabinet_communal_areas_path, notice: I18n.t('created') }
        format.json { render :show, status: :created, location: @cabinet_communal_area }
      else
        format.html { render :new }
        format.json { render json: @cabinet_communal_area.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if status_valid?(create_params[:status]) && @cabinet_communal_area.update(create_params)
        QuestionnaireImages.build(params, @cabinet_communal_area)
        delete_main_image?(create_params[:main_image], @cabinet_communal_area)
        @cabinet_communal_area.update(user_id: current_user.id) unless @cabinet_communal_area.user
        public_send(params[:communal_area][:status])
        format.html { redirect_to cabinet_communal_areas_path, notice: I18n.t('updated') }
        format.json { render :show, status: :ok, location: @cabinet_communal_area }
      else
        format.html { render :edit }
        format.json { render json: @cabinet_communal_area.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cabinet_communal_area.destroy
    respond_to do |format|
      format.html { redirect_to cabinet_communal_areas_path, notice: I18n.t('deleted') }
      format.json { head :no_content }
    end
  end

  def instance
    @cabinet_communal_area
  end

  private

  def set_cabinet_communal_area
    @cabinet_communal_area = CommunalArea.find(params[:id])
  end

  def create_params
    permitted = CommunalArea.globalize_attribute_names + [:house_number, :prop_registration, :cadastral_number, :area,
                                                          :rate_percent, :year_tax, :operation_year, :level,
                                                          :tech_area, :build_year, :architectural, :land_category_id,
                                                          :balance_holder_id, :communal_branch_id, :map_layer_id,
                                                          :main_image, :gis_type_name, :user_id, :status, :site,
                                                          questionnaire_images_attributes: %i[id imgable_type
                                                                                              imgable_id _destroy],
                                                          questionnaire_file_attributes: %i[id fileable_type file
                                                                                            fileable_id _destroy],
                                                          geo_json_attributes: %i[id geo_type position],
                                                          balancer_ids: []]
    params.require(:communal_area).permit(permitted)
  end

  def select_selected_fields
    @land_categories = LandCategory.all.map { |e| [e.name, e.id] }
    @communal_branchs = CommunalBranch.all.map { |e| [e.name, e.id] }
    @balance_holders = BalanceHolder.all.map { |e| [e.name, e.id] }
  end
end

app/controllers/cabinet/geo_json_controller.rb
class Cabinet::GeoJsonController < Cabinet::CabinetController
  def index
    object = params[:model].constantize.find_by(id: params[:id].to_i)
    collection = GeoInfoSystemSerializer.new([object]).serializable_hash[:data].map { |featur| featur[:attributes] }
    render json: { type: 'FeatureCollection', features: collection }
  end
end

app/controllers/cabinet/home_controller.rb
module Cabinet
  class HomeController < Cabinet::CabinetController
    def index; end
  end
end

app/controllers/cabinet/infrastructure_types_controller.rb
class Cabinet::InfrastructureTypesController < Cabinet::CabinetController
  before_action :set_cabinet_infrastructure_type, only: %i[edit update]
  load_and_authorize_resource param_method: :cabinet_infrastructure_type_params

  # GET /cabinet/infrastructure_types
  # GET /cabinet/infrastructure_types.json
  def index
    @cabinet_infrastructure_types = InfrastructureType.all
  end

  # GET /cabinet/infrastructure_types/new
  def new
    @cabinet_infrastructure_type = InfrastructureType.new
  end

  # GET /cabinet/infrastructure_types/1/edit
  def edit; end

  # POST /cabinet/infrastructure_types
  # POST /cabinet/infrastructure_types.json
  def create
    @cabinet_infrastructure_type = InfrastructureType.new(cabinet_infrastructure_type_params)

    respond_to do |format|
      if @cabinet_infrastructure_type.save
        format.html { redirect_to cabinet_infrastructure_types_path, notice: I18n.t('created') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /cabinet/infrastructure_types/1
  # PATCH/PUT /cabinet/infrastructure_types/1.json
  def update
    respond_to do |format|
      if @cabinet_infrastructure_type.update(cabinet_infrastructure_type_params)
        format.html { redirect_to cabinet_infrastructure_types_path, notice: I18n.t('updated') }
      else
        format.html { render :edit }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cabinet_infrastructure_type
    @cabinet_infrastructure_type = InfrastructureType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cabinet_infrastructure_type_params
    params.require(:infrastructure_type).permit(InfrastructureType.globalize_attribute_names)
  end
end

app/controllers/cabinet/map_layer_groups_controller.rb
class Cabinet::MapLayerGroupsController < Cabinet::CabinetController
  load_and_authorize_resource
  before_action :set_cabinet_map_layer_group, only: %i[show edit update]

  def index
    @cabinet_map_layer_groups = MapLayerGroup.all
  end

  def show; end

  def new
    @cabinet_map_layer_group = MapLayerGroup.new
  end

  def edit; end

  def create
    @cabinet_map_layer_group = MapLayerGroup.new(create_params)

    respond_to do |format|
      if @cabinet_map_layer_group.save
        format.html { redirect_to cabinet_map_layer_groups_path, notice: I18n.t('created') }
        format.json { render :show, status: :created, location: @cabinet_map_layer_group }
      else
        format.html { render :new }
        format.json { render json: @cabinet_map_layer_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cabinet_map_layer_group.update(create_params)
        format.html { redirect_to cabinet_map_layer_groups_path, notice: I18n.t('updated') }
        format.json { render :show, status: :ok, location: @cabinet_map_layer_group }
      else
        format.html { render :edit }
        format.json { render json: @cabinet_map_layer_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cabinet_map_layer_group.destroy
    respond_to do |format|
      format.html { redirect_to cabinet_map_layer_groups_path, notice: I18n.t('deleted') }
      format.json { head :no_content }
    end
  end

  private

  def set_cabinet_map_layer_group
    @cabinet_map_layer_group = MapLayerGroup.find(params[:id])
  end

  def create_params
    params.require(:map_layer_group).permit(:title_uk, :title_en, :alias)
  end
end

app/controllers/cabinet/ownerships_controller.rb
class Cabinet::OwnershipsController < Cabinet::CabinetController
  before_action :set_cabinet_ownership, only: %i[edit update]
  load_and_authorize_resource param_method: :cabinet_ownership_params

  # GET /cabinet/ownerships
  # GET /cabinet/ownerships.json
  def index
    @cabinet_ownerships = Ownership.all
  end

  # GET /cabinet/ownerships/new
  def new
    @cabinet_ownership = Ownership.new
  end

  # GET /cabinet/ownerships/1/edit
  def edit; end

  # POST /cabinet/ownerships
  # POST /cabinet/ownerships.json
  def create
    @cabinet_ownership = Ownership.new(cabinet_ownership_params)

    respond_to do |format|
      if @cabinet_ownership.save
        format.html { redirect_to cabinet_ownerships_path, notice: I18n.t('created') }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /cabinet/ownerships/1
  # PATCH/PUT /cabinet/ownerships/1.json
  def update
    respond_to do |format|
      if @cabinet_ownership.update(cabinet_ownership_params)
        format.html { redirect_to cabinet_ownerships_path, notice: I18n.t('updated') }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /cabinet/ownerships/1
  # DELETE /cabinet/ownerships/1.json
  # def destroy
  #   @cabinet_ownership.destroy
  #   respond_to do |format|
  #     format.html { redirect_to cabinet_ownerships_path, notice: 'Ownership was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cabinet_ownership
    @cabinet_ownership = Ownership.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cabinet_ownership_params
    params.require(:ownership).permit(Ownership.globalize_attribute_names)
  end
end

app/controllers/office_areas_controller.rb
class OfficeAreasController < ApplicationController
  def show
    @area = OfficeArea.find_by(id: params[:id])
  end
end

app/views/cabinet/office_areas/_form.html.slim
scss:
  .active-checkbox{
    margin-top: 10px;
  }
  .one-row{
    min-height: 66.45px;
  }

  .char{
    vertical-align: bottom;
    display: inline-block;
    float: none;
  }

  .image-field{
    padding-left: 15px;
    height: 50px;
    margin-top: 15px;
    #office_area_project_images_image{
      display: inline-block;
      margin-left: 15px;
    }
  }

  .filename{
    margin: 0 5px;
  }

  .state-chose {
    padding-top: 15px;
    .text {
      margin-right: 10px;
    }
    .radio {
      margin-right: 10px;
    }
  }

= simple_form_for [:cabinet, @cabinet_office_area] do |f|
  .form-inputs
    .row
      .col-md-2.char
        = f.label :edrpou_code, 'Код ЄДРПОУ'
        = f.input :edrpou_code, label: false, input_html: {class: 'form-control'}
      .col-md-4.char
        = f.label :site, 'Веб-сайт'
        = f.input :site, label: false, input_html: {class: 'form-control'}
      .col-md-2.char
        = f.label :total_area, 'Площа офісного приміщення, м2'
        = f.input :total_area, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :phone, 'Мобільний телефон'
        = f.input :phone, label: false, input_html: {class: 'form-control'}
      .col-md-2.char
        = f.label :email, 'E-mail'
        = f.input :email, label: false, input_html: {class: 'form-control'}
    .row
      .col-md-4.char
        = f.label :city_center_distance, 'Відстань до центральної частини міста, км'
        = f.input :city_center_distance, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-4.char
        = f.label :transport_stop_distance, 'Відстань до зупинки міського транспорту, м'
        = f.input :transport_stop_distance, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :rent, 'Вартість оренди за 1 м2: грн/дол. США'
        = f.input :rent, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :sale, 'Вартість продажу: грн/дол. США'
        = f.input :sale, label: false, input_html: {class: 'form-control decimal-value'}
    .row
      .col-md-2.char
        = f.label :electricity_cost, 'Електроенергія, грн/міс.'
        = f.input :electricity_cost, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :gas_cost, 'Газопостачання, грн/міс.'
        = f.input :gas_cost, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :water_cost, 'Водопостачання, грн/міс.'
        = f.input :water_cost, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :drainager_cost, 'Водовідведення, грн/міс.'
        = f.input :drainager_cost, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :heat_cost, 'Теплопостачання, грн/міс.'
        = f.input :heat_cost, label: false, input_html: {class: 'form-control decimal-value'}
      .col-md-2.char
        = f.label :date_info, 'Дата підготовки інформації'
        = f.input :date_info, as: :string, label: false, input_html: {class: 'form-control'}

    = render 'cabinet/blocks/form/infrastructures', f: f

    .panel-body
      .tab-block.mb25
        .row
          .col-md-6
            h4
              | Українською
            = render 'form_uk', f: f
          .col-md-6
            h4
              | Англійською
            = render 'form_en', f: f

    input#geo_type type='hidden' name='office_area[geo_json_attributes][geo_type]'
    input#position type='hidden' name='office_area[geo_json_attributes][position]'

    = render 'cabinet/blocks/form/croped_image', f: f, area: @cabinet_office_area
  = render 'cabinet/blocks/form/images', f: f, area: @cabinet_office_area

  = f.fields_for :questionnaire_file, @cabinet_office_area.questionnaire_file || @cabinet_office_area.build_questionnaire_file do |ff|
    = ff.input :fileable_type, as: :hidden
    = ff.input :fileable_id, as: :hidden
    .row.pdf-file-field
      .form-inputs.image-field
        = ff.input :file, as: :file, label: 'PDF файл'
      .col-md-12.notice
        .errors
          = f.error :"questionnaire_file.file"
        .view-file
          - unless @cabinet_office_area.questionnaire_file.new_record?
            = link_to @cabinet_office_area.questionnaire_file.file.url, target: :_blank do
              = "Переглянути файл #{@cabinet_office_area.questionnaire_file.file.file.original_filename}"

  - unless @cabinet_office_area.questionnaire_file.new_record?
    = f.fields_for :questionnaire_file, @cabinet_office_area.questionnaire_file do |fd|
      .checkbox.pad-btm.text-left
        = fd.check_box :_destroy, as: :boolean, class: 'magic-checkbox'
        = fd.label :_destroy, "Видалити файл #{fd.object.file.file.original_filename}"
      = fd.input :id, as: :hidden

  / MAP block
  = render 'cabinet/blocks/form/gis_types', f: f
  = render 'cabinet/blocks/form/geo_json', f: f, area: @cabinet_office_area
  = render 'cabinet/blocks/form/map'
  = render 'cabinet/blocks/form/map_layer', f: f
  = render 'cabinet/blocks/form/balancers', f: f
  = render 'cabinet/blocks/form/states', area: @cabinet_office_area

  .form-actions.save_button
    = render 'blocks/btns/save_button', f: f

= javascript_include_tag 'application/google_map_form'
javascript:
  hide_gis_types();

  function initMapForAreas(){
    var AreaMap = initMap();
    var model = "#{@cabinet_office_area.model_name.name}";
    var id = "#{@cabinet_office_area.id}";
    init_map_object(model, id, AreaMap);
  }

  $(document).ready(function () {
    initMonthYearPicker('#office_area_date_info', '#{@cabinet_office_area.date_info}');
    initCropper('#office_area_main_image', {width: 300, height: 200});
    decimal_cut('input[type="text"].decimal-value', 2);

    $('#office_area_map_layer_id').select2({width: '100%'});
    $('#office_area_balancer_ids, #office_area_infrastructure_type_ids').select2({ width: '100%', multiple: true });

    $("#office_area_phone").mask("+38(999)999-99-99");

    $('input[type="text"].decimal-value').change(function () {
        cut_negative_value($(this))
    });

    ready_map_functions()
  });

script async=true defer=true src="https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAP_API']}&libraries=drawing&callback=initMapForAreas"

app/views/cabinet/office_areas/_form_en.html.slim
.row
  .col-md-12
    = f.label :address_en, 'Поштова адреса'
    = f.input :address_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :owner_en, 'Власник'
    = f.input :owner_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :name_en, 'Ім`я, прізвище'
    = f.input :name_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :transfer_type_en, 'Оренда, продаж, інше (зазначте)'
    = f.input :transfer_type_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :gas_en, 'Наявність газопостачання'
    = f.input :gas_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :electricity_en, 'Наявність електропостачання'
    = f.input :electricity_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :water_supply_en, 'Наявність водопостачання'
    = f.input :water_supply_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :drainager_en, 'Наявність водовідведення'
    = f.input :drainager_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :heat_supply_en, 'Наявність теплопостачання'
    = f.input :heat_supply_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :ethernet_en, 'Наявність інтернету'
    = f.input :ethernet_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :phone_sypply_en, 'Наявність телефону'
    = f.input :phone_sypply_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :area_class_en, 'Клас офісного приміщення'
    = f.input :area_class_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :ventilation_en, 'Вентиляційна система'
    = f.input :ventilation_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :fireproof_en, 'Протипожежна система'
    = f.input :fireproof_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :guard_en, 'Охоронна система'
    = f.input :guard_en, label: false, input_html: {class: 'form-control'}
  .col-md-12
    = f.label :parking_en, 'Наявність території для паркування автомобільного транспорту/кількість паркомісць'
    = f.input :parking_en, label: false, input_html: {class: 'form-control'}

app/views/cabinet/office_areas/_table.html.slim
- @cabinet_office_areas.each do |area|
  tr
    td
      = area.address
    td
      = I18n.t('states.' + area.state)
    td
      = true_false(area.map_layer.try :active)
    td
      = balancer_names area.balancers
    td
      = area.map_layer.title
    td
      - if can? :edit, area
        = render 'layouts/blocks/action_btns' do
          = render 'blocks/btns/edit', path: edit_cabinet_office_area_path(area)
          = render 'blocks/btns/delete', path: cabinet_office_area_path(area)

app/views/cabinet/office_areas/edit.html.slim
h1.center
  | Редагувати анкету офісного приміщення

= render 'form'

app/views/cabinet/office_areas/index.html.slim
h1.center Список офісних приміщень

= render 'layouts/general/filter_table', path: (can? :new, OfficeArea) ? new_cabinet_office_area_path : nil, title: '' do
  thead
    tr
      th Адреса
      th Статус
      th Активний тип об'єкту
      th Структурний підрозділ
      th Шар на карті
      th Дії
  tbody
    = render 'table'

app/views/cabinet/office_areas/new.html.slim
h1.center
  | Додати анкету офісного приміщення

= render 'form'

app/views/cabinet/office_areas/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_cabinet_production_area_path(@cabinet_office_area)
'|
=< link_to 'Back', cabinet_production_areas_path