config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'home#index'

  get 'edit_profile/:id', to: 'profiles#edit_profile', as: 'edit_profile'
  put 'update_profile/:id', to: 'profiles#update_profile', as: 'update_profile'
  get 'advantage/:id', to: 'advantages#show', as: 'advantage'
  get '/projects/:alias', to: 'projects#show', as: 'projects'
  post '/feedback', to: 'feedback#send_feedback'
  resources :subscribers, only: :create

  namespace :admin do
    root to: 'home#index'
    resources :menus
    resources :materials
    resources :tags, except: :show
    resources :users, only: %i[index edit update]
    resources :sliders, except: :show
    resources :articles
    resources :videos
    resources :advantages
    resources :projects
    resources :potential_investors, only: %i[index show]
    resources :submission_projects, only: %i[index show]
    resources :contents, only: %i[index edit update]
    resources :departments
    resources :teams
    resources :reviews
    resources :block_materials
    resources :balancers
    resources :sectors, exept: %i[show]
    resources :trips, exept: %i[show]
    resources :landmarks, exept: %i[show]
    resources :period_events, exept: %i[show]
    resources :abouts, exept: %i[show new create]
  end

  namespace :cabinet do
    root to: 'home#index'
    resources :production_areas
    resources :land_areas
    resources :office_areas
    resources :communal_areas
    get 'geo_json/:model/:id', to: 'geo_json#index'
    resources :users, only: %i[index edit update]
    resources :map_layers, except: %i[show]
    resources :potential_investors, only: %i[index show]
    resources :submission_projects, only: %i[index show]
    resources :balancers
    resources :area_logs, only: :index
    resources :communal_areas
    resources :transports
    resources :ownerships
    resources :infrastructure_types
    resources :invest_projects
    resources :map_layer_groups
  end

  namespace :api do
    namespace :v1 do
      resources :map_objects, only: :index
      get '/map_objects/:model/:id', to: 'map_objects#show'
      get '/layer_links', to: 'map_objects#layer_links'
    end
  end

  scope '(:locale)', locale: /uk|en/ do
    get '/guide', to: 'home#guide'
    get '/tourism', to: 'home#tourism'
    get '/about', to: 'abouts#index'
    get 'geo_json_gis', to: 'maps#geo_json_gis', as: :geo_json_gis
    get 'init_map_layers', to: 'maps#map_layers', as: :init_map_layers
    get 'select_object_info', to: 'invest_maps#select_object_info', as: :select_object_info
    root to: 'home#index'
    resources :invest_maps, only: :index
    resources :production_areas, only: :show
    resources :land_areas, only: :show
    resources :office_areas, only: :show
    resources :communal_areas, only: :show
    resources :invest_projects, only: :show
    resources :projects, only: :index
    resources :landmarks, only: :index
    get '/projects/:alias', to: 'projects#show'
    resources :sectors, only: %i[index]
    get 'articles', to: 'articles#index', as: :articles
    get 'articles/:id', to: 'articles#show', as: :article
    resources :user_land_areas, only: :create
    resources :potential_investors, only: :create
    get 'reviews', to: 'reviews#index', as: 'reviews'
    resources :submission_projects, only: :create
    get 'our_team', to: 'teams#index', as: 'our_team'
    get '/search', to: 'elastic#search', as: :search
    resources :materials, only: %i[index]
    resources :materials, only: :show, path: '/'
  end

  match '*path', to: 'application#not_found', via: :all
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController
  def index; end
end

app/controllers/cabinet/home_controller.rb
module Cabinet
  class HomeController < Cabinet::CabinetController
    def index; end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # def index
  #   @sliders = Slider.joins(:project_images).where('project_images.locale' => I18n.default_locale)
  #   @main_video = Video.position('main')
  #   @articles = Article.published_now.first(3)
  #   @advantages = Advantage.order(id: :asc)
  #   @map_content = Content.find_by(alias: 'map')
  #   @teams_without_department = Team.on_main.order(:trim).take(3)
  #   @reviews = Review.all
  # end

  def index
    @reviews = Review.all
    @main_video = Video.position('main')
    @contents = Contents::IndexPresenter.new
  end

  def guide; end

  def tourism
    @landmarks = Landmark.for_tourism.page(params[:page]).per(4)
    @content = Content.for_tourism
    @period_events = PeriodEvent.for_tourism
    @trips = Trip.for_tourism
  end
end

app/views/home/blocks/_big_btn.html.slim
scss:
  .home-big-btn{
    a{
      min-width: 217px;
      background: #b4000f;
      padding: 13px;
      font-size: 18px;
      text-align: center;
      &:hover{
        font-weight: bold;
        background-color: #b4000f;
        border-color: #b4000f;
      }
    }
  }

.home-big-btn
  = link_to path, class: 'btn btn-danger', target: ((defined? target) ? target : '') do
    = text

app/views/home/blocks/_land_area_form.html.slim
- @object = UserLandArea.new
= simple_form_for(@object, remote: true, authenticity_token: true, format: :js) do |f|
  - @object.attributes.except('id', 'created_at', 'updated_at').each do |k,v|
    .row.one-row
      .col-md-6.for-label
        label
          = I18n.t('land_areas.'+ k +'.title', default: '')
      .col-md-6
        = f.input :"#{k}", label: false,
                input_html:{class: @object.decimal_fields.include?(k) ? 'decimal-input' : ''},
                placeholder: I18n.t('land_areas.'+ k +'.desc', default: '')

app/views/home/blocks/_potential_invest_form.html.slim
- @object = PotentialInvestor.new
= simple_form_for(@object, remote: true, authenticity_token: true, format: :js) do |f|
  - @object.attributes.except('id').each do |k,v|
    .row.one-row
      .col-md-6.for-label
        label
          = I18n.t('potential_investor.'+ k +'.title', default: '')
      .col-md-6
        = f.input :"#{k}", label: false,
                input_html:{class: @object.decimal_fields.include?(k) ? 'decimal-input' : ''},
                placeholder: I18n.t('potential_investor.'+ k +'.desc', default: '')
  .additional-fields
    .row
      .col-md-12
        .additional_title.center
          span = I18n.t('potential_investor.second_form.title')
        p = I18n.t('potential_investor.second_form.desc')
    = f.simple_fields_for :representative, @object.build_representative do |ff|
      - @object.build_representative.attributes.except('id', 'potential_investor_id').each do |k,v|
        - unless k == 'additional'
          .row.one-row
            .col-md-6.for-label
              label
                = I18n.t('potential_investor.' + k + '.title', default: '')
            .col-md-6
              = ff.input :"#{k}", label: false, placeholder: I18n.t('potential_investor.'+ k +'.desc', default: '')
      .row.one-row
        .col-md-6.for-label
          label
            = I18n.t('potential_investor.second_form.additional_file', default: '')
        .col-md-6
          = ff.input :additional, as: :file, label: false

app/views/home/blocks/_shared_meta_info.html.slim
= content_for :og_title do
  = seo_friendly_title(title)

= content_for :og_description do
  = seo_friendly_title(description)

= content_for :twitter_title do
  = seo_friendly_title(title)

= content_for :twitter_description do
  = seo_friendly_title(description)

app/views/home/blocks/_sharing_info.html.slim
= tag :meta,
  property: 'og:title',
  content: raw("#{ symbol_code_butcher(yield(:og_title))}")
= tag :meta,
  property: 'og:description',
  content: raw("#{ symbol_code_butcher(yield(:og_description))}")
= tag :meta,
  property: 'og:image',
  content: "#{image_url(yield(:image_facebook)).presence || image_url('invest_logo.png')}"
= tag :meta,
  property: 'og:url',
  content: "#{yield(:share_url)}"
= tag :meta,
  property: 'og:type',
  content: "Article"

= tag :meta,
  name: 'twitter:card',
  content: 'summary'
= tag :meta,
  name: 'twitter:title',
  content: raw("#{ symbol_code_butcher(yield(:twitter_title)) }")
= tag :meta,
  name: 'twitter:description',
  content: raw("#{ symbol_code_butcher(yield(:twitter_description))}")
= tag :meta,
  name: 'twitter:image',
  content: "#{image_url(yield(:image_twitter)).presence || (request.protocol + request.host_with_port + image_path('invest_logo.png'))}"

app/views/home/blocks/_submission_project_form.html.slim
- @object = SubmissionProject.new
= simple_form_for(@object, remote: true, authenticity_token: true, format: :js) do |f|
  - @object.attributes.except('id', 'created_at', 'updated_at').each do |k,v|
    .row.one-row
      .col-md-6.for-label
        label
          = I18n.t('submission_projects.'+ k +'.title', default: '')
      .col-md-6
        = f.input :"#{k}", label: false,
                input_html:{class: @object.decimal_fields.include?(k) ? 'decimal-input' : ''},
                placeholder: I18n.t('submission_projects.'+ k +'.desc', default: '')

app/views/home/blocks/articles.html.slim
#articles
  h2.block-header
    = I18n.t('home.news')
  .container
    .row
      - @articles.each do |article|
        .col-md-4.article
          p= article.publication_time.strftime("%d-%m-%Y")
          = link_to article_path(article) do
            .image-container.effect
              = image_tag article.project_images.by_locale(locale).first.image_url if  article.project_images.by_locale(locale).first
              .mask
              .title
                = link_to article.title, article_path(article)
    .text-center
      = render partial: 'home/blocks/big_btn', locals: {text: t('home.btns.more_news'), path: articles_path}

app/views/home/blocks/invest_offers.html.slim
scss:
  .hidden {
    display: none;
  }
  .invest_offers_button{
    width: 100%;
  }
  #nav-area, #nav-profile, #nav-contact{
    .one-row{
      flex-wrap: initial;
      margin-bottom: 10px;
      .for-label {
        line-height: 22px;
        label {
          font-size: 22px;
          margin-bottom: 0;
        }
      }
      input::-webkit-input-placeholder {
        font-size: 12px;
      }
      input:-ms-input-placeholder {
        font-size: 12px;
      }
      input:-moz-placeholder {
        font-size: 12px;
      }
      input::-moz-placeholder{
        font-size: 12px;
      }
      textarea{
        width: 100%;
      }

      textarea::-webkit-input-placeholder {
        font-size: 12px;
      }
      textarea:-ms-input-placeholder {
        font-size: 12px;
      }
      textarea:-moz-placeholder {
        font-size: 12px;
      }
      textarea::-moz-placeholder {
        font-size: 12px;
      }
    }
    .additional-fields{
      color: #999;
      p{
        text-align: justify;
        line-height: 22px;
      }
      .additional_title{
        font-size: 26px;
      }
    }
  }

  @media screen and (max-width: 767px){
    #nav-profile {
      .one-row {
        height: 100px;
        .for-label {
          label {
            font-size: 16px;
          }
        }
      }
    }

    #nav-contact {
      .one-row {
        height: 100px;
        .for-label {
          label {
            font-size: 16px;
          }
        }
      }
    }
  }

#invest_offers
  .container
    h2.block-header
      = t('home.invest_offers_header')
    .col-md-12
      nav
        #nav-tab.nav.nav-tabs.row[role="tablist"]
          a#nav-area-tab.col-md-4.nav-item.nav-link.active[data-toggle="tab" href="#nav-area" role="tab" aria-controls="nav-area" aria-selected="false"]
            .icon-block
              = inline_svg 'feedback_icons/land_area.svg'
            .title-block
              = t('home.land_area')
          a#nav-profile-tab.col-md-4.nav-item.nav-link[data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"]
            .icon-block
              = inline_svg 'feedback_icons/investor_form.svg'
            .title-block
              = t('home.potential_investor')
          a#nav-contact-tab.col-md-4.nav-item.nav-link[data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false"]
            .icon-block
              = inline_svg 'feedback_icons/invest_project_form.svg'
            .title-block
              = t('home.investment_project')
      #nav-tabContent.tab-content.row.hidden
        #nav-area.tab-pane.fade.show.active[role="tabpanel" aria-labelledby="nav-area-tab"]
          = render 'home/blocks/land_area_form'
        #nav-profile.tab-pane.fade[role="tabpanel" aria-labelledby="nav-profile-tab"]
          = render 'home/blocks/potential_invest_form'
        #nav-contact.tab-pane.fade[role="tabpanel" aria-labelledby="nav-contact-tab"]
          = render 'home/blocks/submission_project_form'
        .text-center.invest_offers_button#invest_offers_button
          = render partial: 'home/blocks/big_btn', locals: { text: t('home.btns.send'), path: '#' }

#answer_offers.modal.fade aria-hidden="true" aria-labelledby="answerOffersModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      button.close aria-label="Close" data-dismiss="modal" type="button"
        span aria-hidden="true"  &times;
      .modal-answer-title
        = t('home.feedback_form.offer_title')
      .modal-answer-description
        = t('home.feedback_form.answer_description')

javascript:
  decimal_cut('input[type="text"].decimal-input', 2);
  $('#potential_investor_phone, #potential_investor_representative_attributes_phone,' +
    '#submission_project_phone, #user_land_area_phone, #potential_investor_fax,' +
    '#potential_investor_representative_attributes_fax').mask("+38(999)999-99-99");

  $('#invest_offers .home-big-btn a').click(function (e) {
    e.preventDefault();
    var tab_id = $("#nav-tab a.active").attr('href');
    $(tab_id + ' form').submit();
    $("#answer_offers").modal();
  });

  function showOffers() {
    $('#nav-tabContent').removeClass('hidden');
  }

  $('#nav-area-tab, #nav-profile-tab, #nav-contact-tab').on('click', function () {
    showOffers();
  });

app/views/home/blocks/our_team.html.slim
.our_team
  .container
    h2.block-header
      = t('home.our_team')
    .row.slick-teams
      = render @teams_without_department
    .text-center
      = render partial: 'home/blocks/big_btn', locals: {text: t('home.btns.show_all'), path: '/our_team'}